version: '3.8'

services:
  # Django Backend
  backend:
    build:
      context: .  # Set build context to the root of the project (icb-app)
      dockerfile: backend/Dockerfile  # Explicitly set path to Dockerfile inside the backend folder
    container_name: backend
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=mydatabase
      - DB_USER=django_user
      - DB_PASSWORD=django_password
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - app-network

  # PostgreSQL Database
  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data  # This is the volume to persist data
    networks:
      - app-network

  # Frontend (React)
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

volumes:
  postgres-data:  # Declare the volume for persistent data

networks:
  app-network:
    driver: bridge
