# Generated by Django 5.1.4 on 2025-01-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_player_city_player_home_arcade_player_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='instagram_handle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='twitch_handle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='youtube_handle',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
