# Generated by Django 5.1.4 on 2025-01-07 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_player_instagram_handle_player_twitch_handle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='player',
            name='twitch',
        ),
        migrations.RemoveField(
            model_name='player',
            name='youtube',
        ),
    ]
