# Generated by Django 5.1.4 on 2025-01-07 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_remove_player_instagram_remove_player_twitch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='instagram_handle',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='twitch_handle',
            new_name='twitch',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='youtube_handle',
            new_name='youtube',
        ),
    ]
